(defun fg ()
  (interactive)
  (read-only-mode -1)
  (flush-lines ".*~")
  (flush-lines "\\.xml")
  (flush-lines "app\\.c")
  (flush-lines "main\\.\\(bin\\|exe\\|ihex\\|lst\\|map\\|sym\\)")
  (flush-lines "binary")
  (flush-lines "doc/txt/tep")
  (flush-lines "\\.html")
  (flush-lines "\\.git")
  (flush-lines "doc/nesdoc")
  (flush-lines "deprecated"))
