(setq make-command ". ~/.environment_bash; make exp5438_gps && mspdebug uif -jd /dev/ttyUSB0 \"prog build/exp5438_gps/main.exe\"")
(setq make-command ". ~/.environment_bash; make mm5a  && mspdebug uif -d /dev/ttyUSB0 \"prog build/mm5a/main.exe\"")
;;;(setq gud-gdb-command-name "msp430-gdb -i=mi build/mm5a/main.exe")
(setq make-command ". ~/.environment_bash; make -k -Wall")
(setq make-command "gcc -o align -ggdb -Wall -m32 align.c")
;;;(setq gud-gdb-command-name "gdb -i=mi align")
(setq make-command ". ~/.environment_bash; make sam3u_ek")
;;;(setq gud-gdb-command-name "arm-none-eabi-gdb -i=mi build/sam3u_ek/main.exe")
(setq make-command ". ~/.environment_bash; make exp_msp432")
(setq gud-gdb-command-name "arm-none-eabi-gdb-py -i=mi build/exp_msp432/main.exe")
