(setq make-command ". ~/.environment_bash; make -k -Wall")
(setq make-command "gcc -o align -ggdb -Wall -m32 align.c")
(setq make-command ". ~/.environment_bash; make mm6a")
(setq gud-gdb-command-name "arm-none-eabi-gdb-py -i=mi build/mm6a/main.exe")
(setq make-command ". ~/.environment_bash; make dev6a")
(setq gud-gdb-command-name "arm-none-eabi-gdb-py -i=mi build/dev6a/main.exe")
