;;; boon-claude.el --- Claude CLI helpers -*- lexical-binding: t; -*-
(require 'magit nil t)
(require 'transient nil t)
(defun boon/claude--call (skill input)
  (with-temp-buffer
    (insert input)
    (let ((exit (call-process-region (point-min) (point-max) "claude" t t nil skill)))
      (if (and (integerp exit) (= exit 0)) (buffer-string)
        (format "Error calling `claude` (exit=%s). Ensure CLI is installed and you ran `claude /login`." exit)))))
(defun boon/claude--display (title text)
  (let ((buf (get-buffer-create "*Claude*")))
    (with-current-buffer buf
      (read-only-mode -1) (erase-buffer)
      (insert (format "# %s\n\n%s" title text))
      (when (fboundp 'markdown-mode) (markdown-mode))
      (goto-char (point-min)) (read-only-mode 1))
    (display-buffer buf)))
(defun boon/claude-on-staged (skill)
  (interactive "sSkill (e.g., /review): ")
  (let* ((default-directory (or (and (fboundp 'magit-toplevel) (magit-toplevel)) default-directory))
         (diff (and (fboundp 'magit-git-string) (magit-git-string "diff" "--cached"))))
    (unless diff (user-error "No staged changes. Stage with 's' in Magit"))
    (boon/claude--display skill (boon/claude--call skill diff))))
(defun boon/claude-on-buffer (skill)
  (interactive "sSkill (e.g., /review): ")
  (boon/claude--display skill (boon/claude--call skill (buffer-string))))
(defun boon/claude-on-region (skill beg end)
  (interactive "sSkill (e.g., /review): \nr")
  (boon/claude--display skill (boon/claude--call skill (buffer-substring-no-properties beg end))))
(transient-define-prefix boon/claude-menu ()
  "Claude helpers"
  ["Run skill"
   ("s" "On STAGED (/review)" (lambda () (interactive) (boon/claude-on-staged "/review")))
   ("c" "Commit msg (/commit)" (lambda () (interactive) (boon/magit-ai-commit-message)))
   ("b" "On BUFFER (/review)"  (lambda () (interactive) (boon/claude-on-buffer "/review")))
   ("r" "On REGION (prompt)"   boon/claude-on-region)]
  ["Summaries"
   ("l" "Repo SUMMARY (/summary on range)"
    (lambda ()
      (interactive)
      (let* ((default-directory (or (and (fboundp 'magit-toplevel) (magit-toplevel)) default-directory))
             (range (if (fboundp 'magit-rev-read-range)
                        (magit-rev-read-range "Summarize range (e.g., main..HEAD): ")
                      "HEAD~10..HEAD"))
             (log (and (fboundp 'magit-git-string) (magit-git-string "log" "--pretty=medium" range))))
        (unless log (user-error "Empty range"))
        (boon/claude--display "/summary" (boon/claude--call "/summary" log)))))])
(defun boon/magit-ai-commit-message ()
  (interactive)
  (let* ((default-directory (or (and (fboundp 'magit-toplevel) (magit-toplevel)) default-directory))
         (diff (and (fboundp 'magit-git-string) (magit-git-string "diff" "--cached"))))
    (unless diff (user-error "No staged changes. Stage with 's' in Magit"))
    (let ((msg (boon/claude--call "/commit" diff)))
      (if (fboundp 'magit-commit-create)
          (progn (magit-commit-create)
                 (when (derived-mode-p 'git-commit-mode) (erase-buffer) (insert msg) (goto-char (point-min))))
        (message "%s" msg)))))
(defun boon/claude-docs-for-buffer ()
  (interactive)
  (let* ((src (buffer-string))
         (prompt (concat "Generate docstrings for functions/classes in this buffer and a README changelog entry.\n\n" src)))
    (boon/claude--display "/doc" (boon/claude--call "/doc" prompt))))
(defun boon/claude-refactor-region (beg end)
  (interactive "r")
  (let* ((text (buffer-substring-no-properties beg end))
         (resp (boon/claude--call "/refactor" text))
         (buf  (get-buffer-create "*Claude Refactor*")))
  (with-current-buffer buf
    (read-only-mode -1) (erase-buffer) (insert resp) (prog-mode) (read-only-mode 1))
  (display-buffer buf '(display-buffer-pop-up-window . ((side . right) (window-width . 0.5))))))
(provide 'boon-claude)